pipeline{
    agent any
    environment{
    GIT_BRANCH = 'master'
    url = 'https://github.com/Aves4/Amazon_ABC.git'
    SLACK_WEBHOOK = 'https://hooks.slack.com/services/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'
    }
    stages{
        stage('clone project'){
            steps{
                git branch:"${GIT_BRANCH}", url:"${url}"
            }
        }
        stage('compile'){
            steps{
                dir('Amazon'){
                    sh 'mvn compile'
                }
            }
        }
        stage('test'){
            steps{
                dir('Amazon'){
                    sh 'mvn test'
                }
            }
        }
        stage('build'){
            steps{
                dir('Amazon'){
                    sh 'mvn clean install'
                }
            }
        }
    }
    post {
    success {
        sh """
        curl -X POST -H 'Content-type: application/json' \
        --data '{ "text": "Build SUCCESS: ${JOB_NAME} #${BUILD_NUMBER}" }' \
        $SLACK_WEBHOOK
        """
    }
    failure {
        sh """
        curl -X POST -H 'Content-type: application/json' \
        --data '{ "text": "Build FAILED: ${JOB_NAME} #${BUILD_NUMBER}" }' \
        $SLACK_WEBHOOK
        """
    }
}
}

